### ISSUE TITLE
Do not create a new connection for each chunk.

### ISSUE THREAD

**Issue by mcollina** [Xstoudi/pino-pg#2]
Currently the code creates a new connection for each chunk.

This approach is going to fail under high throughput.
I would recommend

1) reuse the connection
2) batch a series of inserts into a single bulk operation

**Comment by Xstoudi** [comment]
Thanks for feedback.
pino-pg transport now keep connection open until work is done.

**Comment by mcollina** [comment]
I would change the implementation a bit to support Node 10 and 12.

**Comment by Xstoudi** [comment]
Done!

**Comment by mcollina** [comment]
awesome, thanks!
